// Minimap journey, the Contact Café: enter, sit, conversation, feedback, contact details; guide quick links + commands.
import { chromium } from 'playwright-core'
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const b = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? 'C:/Program Files/Google/Chrome/Application/chrome.exe', args: ['--use-angle=d3d11'] })
const p = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage()
const errors = []
p.on('pageerror', (e) => errors.push(e.message))
p.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
const where = () => p.evaluate(() => document.querySelector('.ui-where b')?.textContent)
await p.goto('http://localhost:5173/street?debug&desktop&mode=day')
await p.waitForSelector('.ui-intro__skip', { timeout: 90000 })
await p.getByRole('button', { name: 'Skip intro' }).click()
await p.waitForSelector('.ui-intro.is-hero', { timeout: 20000 })
await sleep(1000)
await p.getByRole('button', { name: 'Start exploring' }).click()
await sleep(5000)
console.log('minimap stops:', await p.evaluate(() => [...document.querySelectorAll('.ui-minimap__marker')].map((m) => m.textContent.trim()).join(' | ')))
console.log('minimap here:', await p.evaluate(() => document.querySelector('.ui-minimap__marker.is-here')?.textContent))
await p.screenshot({ path: 'qa-screens/190-start.png' })
await p.screenshot({ path: 'qa-screens/191-minimap.png', clip: { x: 1180, y: 600, width: 260, height: 300 } })
// guide quick links
await p.getByRole('button', { name: /Open your guide/ }).click()
await sleep(500)
console.log('guide quick links:', await p.evaluate(() => [...document.querySelectorAll('.ui-guide__quick button')].map((b) => b.textContent.trim()).join(' | ')))
await p.screenshot({ path: 'qa-screens/192-guide.png' })
await p.getByRole('button', { name: 'Close guide' }).click()
// typed commands
for (const cmd of ['take me home', 'show my education', 'NFC', 'show projects', 'how do you design', "let's connect"]) {
  await p.getByRole('button', { name: /Open your guide/ }).click()
  await sleep(400)
  await p.locator('.ui-guide__ask input').fill(cmd)
  await p.keyboard.press('Enter')
  await sleep(9500)
  console.log(`"${cmd}" →`, await where())
  await p.keyboard.press('Escape')
  await sleep(500)
}
// café: sit and talk (we're inside it after "let's connect")
await p.screenshot({ path: 'qa-screens/193-cafe-inside.png' })
const t = await p.evaluate(() => { const o = [320 + 3.4, 240 - 2.6 + 1.3]; window.__teleport(o[0], o[1] + 0.4, Math.PI); return o })
await sleep(1500)
console.log('prompt:', await p.evaluate(() => document.querySelector('.ui-prompt')?.textContent))
await p.keyboard.press('KeyE')
await sleep(5200)
await p.screenshot({ path: 'qa-screens/194-cafe-sit.png' })
console.log('chat:', await p.evaluate(() => [...document.querySelectorAll('.ui-cafe__chat li')].map((l) => l.textContent).join(' / ')))
await p.locator('.ui-cafe textarea').fill('QA: loved the café ending.')
await p.getByRole('button', { name: 'Send feedback' }).click()
await sleep(1500)
await p.screenshot({ path: 'qa-screens/195-cafe-connect.png' })
console.log('connect:', await p.evaluate(() => document.querySelector('.ui-cafe h2')?.textContent), '|', await p.evaluate(() => [...document.querySelectorAll('.ui-cafe .ui-contact > *')].map((e) => e.querySelector('b')?.textContent ?? e.textContent).join(' · ')))
console.log('feedback saved:', await p.evaluate(() => !!localStorage.getItem('mindscape:feedback')))
await p.getByRole('button', { name: 'Stand up and keep exploring' }).click()
await sleep(1500)
console.log('standing again, controls:', await p.evaluate(() => window.__mindscape.state))
console.log('errors:', errors.length ? errors : 'none')
await b.close()
