// "View my work" → NFC Solutions Project Studio → open a project → tabs → close → back outside.
import { chromium } from 'playwright-core'
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))
const vp = process.argv[2] ? process.argv[2].split('x').map(Number) : [1440, 900]
const b = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? 'C:/Program Files/Google/Chrome/Application/chrome.exe', args: ['--use-angle=d3d11'] })
const p = await (await b.newContext({ viewport: { width: vp[0], height: vp[1] } })).newPage()
const errors = []
p.on('pageerror', (e) => errors.push(e.message))
p.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
const st = () => p.evaluate(() => ({ ...window.__mindscape }))
await p.goto('http://localhost:5173/street?debug&desktop')
await p.waitForFunction(() => window.__intro && window.__intro.running, null, { timeout: 90000 })
await p.keyboard.press('Escape')
await sleep(2400)
await p.getByRole('button', { name: 'View my work' }).click()
await sleep(1500)
await p.screenshot({ path: 'qa-screens/100-viewwork-approach.png' })
await sleep(2200)
await p.screenshot({ path: 'qa-screens/101-studio-establish.png' })
await sleep(3200)
let s = await st()
console.log('in studio at', s.x, s.z)
await p.screenshot({ path: 'qa-screens/102-studio-arrive.png' })
// walk to the first project bay (IntelliStaff) and open it
await p.evaluate(() => window.__teleport(320 + 21.2, -7.6, Math.PI / 2))
await sleep(1800)
await p.screenshot({ path: 'qa-screens/103-studio-bay.png' })
await p.keyboard.press('KeyE')
await sleep(2200)
await p.screenshot({ path: 'qa-screens/104-case-overview.png' })
await p.getByRole('tab', { name: 'Process' }).click()
await sleep(700)
await p.screenshot({ path: 'qa-screens/105-case-process.png' })
await p.getByRole('button', { name: /Next project/ }).click()
await sleep(1800)
await p.screenshot({ path: 'qa-screens/106-case-next.png' })
await p.getByRole('button', { name: 'Close project' }).click()
await sleep(1500)
// the office itself + colleagues
await p.evaluate(() => window.__teleport(320 + 5.0, 4.6, 0.6))
await sleep(2200)
await p.screenshot({ path: 'qa-screens/107-office-colleague.png' })
const tag = await p.evaluate(() => document.querySelector('.ui-nametag.is-visible b')?.textContent ?? null)
console.log('name tag:', tag)
await p.getByRole('button', { name: 'Back outside' }).click()
await sleep(1800)
s = await st()
console.log('after back outside', s.x, s.z)
await p.screenshot({ path: 'qa-screens/108-back-outside.png' })
console.log('errors:', errors.length ? errors : 'none')
await b.close()
